<?= $this->partial('admin/_shared/articles_menu.phtml'); ?>

<div class="col-sm-9">
   
   <table class="table table-striped table-bordered">
      <thead>
         <tr><th>Page name</th><th>URL</th><th>Required</th><th>Actions</th></tr>
      </thead>
      <tbody>
         <?php foreach ($this->pages as $page): ?>
         <tr class="evenRow">
            <td><?= $page['name'] ?></td>
            <td><?= $page['url'] ?></td>
            <td><?= $page['required'] ?></td>
         <td>
            <a href="<?= $this->url('admin/articles', ['action' => 'preview', 'id' => $page['url']]) ?>" title="Preview">
                <span class="fas fa-search"></span>
            </a>
            <?php if ($page['required'] != 1): ?>
             <a href="<?= $this->url('admin/articles', ['action' => 'editpage', 'id' => $page['id']]) ?>" title="Edit Page">
                 <span class="fas fa-edit"></span>
             </a>
            <?php endif; ?>
            <a href="<?= $this->url('admin/articles', ['action' => 'seecontents', 'id' => $page['id']]) ?>" title="Manage Contents">
                <span class="fas fa-cog"></span>
            </a>
            <?php if($page['required'] != 1): ?>
            <a href="<?= $this->url('admin/articles', ['action' => 'delete', 'id' => $page['id']]) ?>" class="confirm" title="Remove Page">
                <span class="fas fa-trash"></span>
            </a>
            <?php endif; ?>
         </td></tr>
         <?php endforeach; ?>
      </tbody>
   </table>

</div>