<?= $this->partial('admin/_shared/articles_menu.phtml'); ?>

<div class="col-sm-9">
   
   <table class="table table-striped table-bordered">
      <thead>
         <tr><th>Content name</th><th>Actions</th></tr>
      </thead>
      <tbody>
         <?php foreach ($this->contents as $content): ?>
         <tr class="evenRow">
            <td><?= $content['name'] ?></td>
            <td>
               <a href="<?= $this->url('admin/articles', ['action' => 'editcontent', 'id' => $content['id']]) ?>" title="edit">
                   <span class="fas fa-edit"></span>
               </a>
               <a href="<?= $this->url('admin/articles', ['action' => 'deletecontent', 'id' => $content['id']]) ?>" class="confirm" title="delete">
                   <span class="fas fa-remove"></span>
               </a>
            </td>
         </tr>
         <?php endforeach; ?>
      </tbody>
   </table>

</div>