<div class="jumbotron">
    <h1><span class="zf-green">New %name_singular_upper%</span></h1>
    <?php
        $userForm->setAttribute('action', $this->url('%name_plural_lower%', ['action' => 'add']));
        $userForm->prepare();
        echo $this->form()->openTag($%name_singular_lower%Form);
        echo $this->formHidden($%name_singular_lower%Form->get('id'));
        
%form_elements%
        
        echo $this->formSubmit($%name_singular_lower%Form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>
