<div class="jumbotron">
    <h1><span class="zf-green">%name_plural_upper%</span></h1>
    <a href="<?= $this->url('%name_plural_lower%', ['action' => 'add']) ?>">Add %name_singular_upper%</a>
    <table class="table">
        <tr>
        <th>Id</th>
        
%table_columns_headings%
        <th>Actions</th>
        
        </tr>
        <?php foreach ($%name_singular_lower%Rows as $%name_singular_lower%): ?>
        <tr>
            <td><?= $%name_singular_lower%->getId() ?></td>
            
%table_columns%
            <td>
                <a href="<?= $this->url('%name_plural_lower%', ['action' => 'edit', 'id' => $%name_singular_lower%->getId()]) ?>">Edit</a> |
                <a href="<?= $this->url('%name_plural_lower%', ['action' => 'delete', 'id' => $%name_singular_lower%->getId()]) ?>">Remove</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
