<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(isset($title) ? $title : 'Laminas Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('description', isset($description) ? $description : 'Default description')
            ->appendName('keywords', isset($keywords) ? $keywords : 'Default key names');
        ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/fontawesome.min.css'))
            ->prependStylesheet($this->basePath('css/all.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
            ->prependFile('http://cdn.ckeditor.com/4.14.0/standard/ckeditor.js')
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" height="28" alt="Laminas Admin Panel"/>&nbsp;Laminas Admin Panel
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('admin_navigation')
                        ->menu()
                        ->setPartial('admin/_shared/menu')
                        ->setMaxDepth(0)
                        ->setRenderInvisible(false) ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                    </button>
                <div>')->setMessageCloseString('</div></div>');

                $flash->clearMessagesFromContainer();
                echo $flash->renderCurrent('error', array('alert', 'alert-dismissable', 'alert-danger'));
                echo $flash->renderCurrent('warning', array('alert', 'alert-dismissable', 'alert-warning'));
                echo $flash->renderCurrent('info', array('alert', 'alert-dismissable', 'alert-info'));
                echo $flash->renderCurrent('default', array('alert', 'alert-dismissable', 'alert-warning'));
                echo $flash->renderCurrent('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>
            <div class="row">
                <?= $this->content ?>
            </div>
            <hr>
            
            <?= $this->partial('admin/_shared/footer.phtml'); ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
